feat: 系统切换黑暗模式时状态栏文字颜色跟着变动
fluttercandies/flutter_juejin pull request #13
Opened 2022-07-29 08:55 UTC by DemoJameson

顺便解决 Android 上 Light 模式状态栏文字也是白色的问题

2022-07-29 09:32 UTC, AlexV525 requested changes

2022-07-29 09:32 UTC, AlexV525 commented on lib/app.dart
> +    final Brightness brightness = WidgetsBinding.instance.window.platformBrightness;
这里需要使用栈内的 `ThemeData`，加入切换模式后不以平台为准。

2022-07-29 09:32 UTC, AlexV525 commented on lib/app.dart
> +  @override
重载的方法写在顶部。

2022-07-29 09:32 UTC, AlexV525 commented on lib/app.dart
> +      child: _buildAnnotatedRegion(
置于 `MaterialApp.builder` 内基于 `BuildContext` 进行构建。

2022-07-29 09:54 UTC, DemoJameson commented on lib/app.dart
> +  @override
写在顶部吗，那 build 方法是特殊的，就它在底部？

2022-07-29 10:33 UTC, AlexV525 commented on lib/app.dart
> +  @override
> 写在顶部吗，那 build 方法是特殊的，就它在底部？

没错

2022-07-29 15:24 UTC, AlexV525 approved these changes

2022-07-29 15:26 UTC, merged

2022-07-29 15:26 UTC, AlexV525 commented
@all-contributors Add @DemoJameson for code and bug.

2022-07-30 00:45 UTC, DemoJameson commented
突然想起通过 themeData 获取 brightness 的话就不需要  with WidgetsBindingObserver 了
因为默认的 ThemeMode.system 本身就会在系统开关黑暗模式时改变使用的 themeData 刷新用户界面
后面你实现切换模式时把那堆重载方法删掉吧