✨ Improve article detail
fluttercandies/flutter_juejin pull request #19
Opened 2022-08-14 09:56 UTC by shirne

1. shor title & infos when content is loading
2. add bottom bar for digg & comment & collect & share
3. show comments

2022-08-19 09:37 UTC, a1017480401 approved these changes

2022-08-19 10:09 UTC, a1017480401 requested changes
The webview of the details page on Android will flash

2022-08-20 04:38 UTC, shirne commented
4. fix comments api's paging parameters

2022-08-20 05:52 UTC, a1017480401 approved these changes

2022-08-20 05:54 UTC, merged